package com.isec.pd22.enums;

public enum ClientsPayloadType {
    REQUEST_SERVERS,
    REQUEST_SERVERS_SUCCESS,
    CONNECTION_LOST,
    BAD_REQUEST,
    LOGGED_IN, TRY_LATER, LOGOUT, FILE_UPDATED, PART_OF_FILE_UPLOADED, USER_REGISTER

}
