package com.isec.pd22.enums;

public enum ClientActions {
    REGISTER_USER, LOGIN, EDIT_USER, CONSULT_UNPAYED_RESERVATION, CONSULT_PAYED_RESERVATION, CONSULT_SPECTACLE, CONSULT_SPECTACLE_DETAILS,
    CHOOSE_SPECTACLE_24H, SUBMIT_RESERVATION, CANCEL_RESERVATION, ADD_SPECTACLE, DELETE_SPECTACLE, SWITCH_VISIBILITY, EXIT, GET_RESERVS, PAY_RESERVATION, LOGOUT
}
