package com.isec.pd22.enums;

public enum ClientActions {
    REGISTER_USER, LOGIN, EDIT_USER, CONSULT_UNPAYED_RESERVATION, CONSULT_PAYED_RESERVATION, CONSULT_SPECTACLE,
    CHOOSE_SPECTACLE_24H, SUBMIT_RESERVATION, CANCEL_RESERVATION, ADD_SPECTACLE, DELETE_SPECTACLE, LOGOUT
}
